{
 "title": "Mikrotik",
 "description": "Mikrotik monitoring (support 9.0.5) added w60G",
 "tags": [
  "mikrotik",
  "snmp"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "DataSource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(mikrotik_system_identity, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SNMP stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "SNMP Scrape Duration",
     "type": "stat",
     "description": "Total SNMP time scrape took (walk and processing)",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "scrape_duration_seconds{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "PDUs Returned",
     "type": "stat",
     "description": "Number of records that were moved from main table to time series",
     "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snmp_scrape_pdus_returned{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Walk Duration",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 7, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snmp_scrape_walk_duration_seconds{instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } }
 ]
}